const actions = {
  GET_JOB_LIST: "GET_JOB_LIST",
  PUT_JOB_LIST: "PUT_JOB_LIST",
  POST_NEW_JOB: "POST_NEW_JOB",
  POST_NEW_JOB_SUCCESS: "POST_NEW_JOB_SUCCESS",
  POST_NEW_JOB_FAIL: "POST_NEW_JOB_FAIL",
  POST_NEW_JOB_REFRESH: "POST_NEW_JOB_REFRESH",
  GET_JOB: "GET_JOB",
  PUT_JOB: "PUT_JOB",
};
export default actions;
